title: "saewa's blog"
email: saewa0424@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Saewa
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  saewa:
    name: Saewa
    display_name: Saewa
    avatar: 'assets/images/sal.png'
    email: saewa0424@gmail.com
    web: https://leesaewa.github.io/
    github: https://github.com/leesaewa/
    description: "I love my job"
    
# Social
social:
  github: https://github.com/leesaewa

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
